In [2]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("database.sqlite")

df1 = pd.read_sql("SELECT * FROM Player", conn)
print("PLAYER")
display(df1.head())

df2 = pd.read_sql("SELECT * FROM Match", conn)
print("MATCH")
display(df2.tail())

df3 = pd.read_sql("SELECT * FROM Team", conn)
print("TEAM")
display(df3)

df4 = pd.read_sql("SELECT * FROM Country", conn)
print("COUNTRY")
display(df4.describe(include="all"))

conn.close()

Table: Player

,Player_Id,Player_Name,DOB,Batting_hand,Bowling_skill,Country_Name
0,1,SC Ganguly,1972-07-08 00:00:00,1,1.0,1
1,2,BB McCullum,1981-09-27 00:00:00,2,1.0,4
2,3,RT Ponting,1974-12-19 00:00:00,2,1.0,5
3,4,DJ Hussey,1977-07-15 00:00:00,2,2.0,5
4,5,Mohammad Hafeez,1980-10-17 00:00:00,2,2.0,6
...,...,...,...,...,...,...
464,465,DL Chahar,1992-08-07 00:00:00,2,1.0,1
465,466,P Dharmani,1974-09-27 00:00:00,2,NaN,1
466,467,RV Pawar,1979-09-06 00:00:00,1,7.0,1
467,468,KH Devdhar,1989-12-14 00:00:00,2,NaN,1
468,469,T Mishra,1986-12-22 00:00:00,2,3.0,1

Table: Extra_Runs

      Match_Id  Over_Id  Ball_Id  Extra_Type_Id  Extra_Runs  Innings_No
0       335987        1        1              1           1           1
1       335987        1        2              2           1           2
2       335987        1        3              2           1           1
3       335987        1        7              1           1           1
4       335987        2        3              1           4           2
...        ...      ...      ...            ...         ...         ...
7464    981024       18        2              2           1           1
7465    981024       18        5              1           1           2
7466    981024       19        4              1           1           2
7467    981024       19        5              2           5           1
7468    981024       20        4              1           1           2

[7469 rows x 6 columns]

Table: Batsman_Scored

        Match_Id  Over_Id  Ball_Id  Runs_Scored  Innings_No
0         335987        1        1            0           1
1         335987        1        1            1           2
2         335987        1        2            0           1
3         335987        1        3            0           2
4         335987        1        4            0           1
...          ...      ...      ...          ...         ...
133092    981024       20        4            0           2
133093    981024       20        5            1           1
133094    981024       20        5            1           2
133095    981024       20        6            6           1
133096    981024       20        6            4           2

[133097 rows x 5 columns]

Table: Batting_Style

   Batting_Id    Batting_hand
0           1   Left-hand bat
1           2  Right-hand bat

Table: Bowling_Style

    Bowling_Id           Bowling_skill
0            1        Right-arm medium
1            2      Right-arm offbreak
2            3   Right-arm fast-medium
3            4         Legbreak googly
4            5   Right-arm medium-fast
5            6    Left-arm fast-medium
6            7  Slow left-arm orthodox
7            8  Slow left-arm chinaman
8            9    Left-arm medium-fast
9           10                Legbreak
10          11          Right-arm fast
11          12        Right-arm bowler
12          13         Left-arm medium
13          14           Left-arm fast

Table: Country

    Country_Id  Country_Name
0            1         India
1            2  South Africa
2            3         U.A.E
3            4   New Zealand
4            5     Australia
5            6      Pakistan
6            7     Sri Lanka
7            8   West Indies
8            9     Zimbabwea
9           10       England
10          11    Bangladesh
11          12   Netherlands

Table: Season

   Season_Id  Man_of_the_Series  Orange_Cap  Purple_Cap  Season_Year
0          1                 32         100         102         2008
1          2                 53          18          61         2009
2          3                133         133         131         2010
3          4                162         162         194         2011
4          5                315         162         190         2012
5          6                 32          19          71         2013
6          7                305          46         364         2014
7          8                334         187          71         2015
8          9                  8           8         299         2016

Table: City

    City_Id       City_Name  Country_id
0         1       Bangalore           1
1         2      Chandigarh           1
2         3           Delhi           1
3         4          Mumbai           1
4         5         Kolkata           1
5         6          Jaipur           1
6         7       Hyderabad           1
7         8         Chennai           1
8         9       Cape Town           2
9        10  Port Elizabeth           2
10       11          Durban           2
11       12       Centurion           2
12       13     East London           2
13       14    Johannesburg           2
14       15       Kimberley           2
15       16    Bloemfontein           2
16       17       Ahmedabad           1
17       18         Cuttack           1
18       19          Nagpur           1
19       20      Dharamsala           1
20       21           Kochi           1
21       22          Indore           1
22       23   Visakhapatnam           1
23       24            Pune           1
24       25          Raipur           1
25       26          Ranchi           1
26       27       Abu Dhabi           3
27       28          Rajkot           1
28       29          Kanpur           1

Table: Outcome

   Outcome_Id Outcome_Type
0           1       Result
1           2    No Result
2           3    Superover

Table: Win_By

   Win_Id   Win_Type
0       1       runs
1       2    wickets
2       3  NO Result
3       4        Tie

Table: Wicket_Taken

      Match_Id  Over_Id  Ball_Id  Player_Out  Kind_Out  Fielders  Innings_No
0       335987        2        1           6         2       NaN           2
1       335987        3        2           8         2       NaN           2
2       335987        5        5           9         1      83.0           2
3       335987        6        2           1         1       9.0           1
4       335987        6        2           7         1       3.0           2
...        ...      ...      ...         ...       ...       ...         ...
6722    981024       17        3          32         1     163.0           2
6723    981024       18        3         183         3      32.0           1
6724    981024       19        1         255         3     394.0           2
6725    981024       19        4         228         1     382.0           1
6726    981024       20        3         434         3     183.0           2

[6727 rows x 7 columns]

Table: Venue

    Venue_Id                                         Venue_Name  City_Id
0          1                              M Chinnaswamy Stadium        1
1          2         Punjab Cricket Association Stadium, Mohali        2
2          3                                   Feroz Shah Kotla        3
3          4                                   Wankhede Stadium        4
4          5                                       Eden Gardens        5
5          6                             Sawai Mansingh Stadium        6
6          7          Rajiv Gandhi International Stadium, Uppal        7
7          8                    MA Chidambaram Stadium, Chepauk        8
8          9                         Dr DY Patil Sports Academy        4
9         10                                           Newlands        9
10        11                                   St George's Park       10
11        12                                          Kingsmead       11
12        13                                    SuperSport Park       12
13        14                                       Buffalo Park       13
14        15                              New Wanderers Stadium       14
15        16                              De Beers Diamond Oval       15
16        17                                    OUTsurance Oval       16
17        18                                  Brabourne Stadium        4
18        19                       Sardar Patel Stadium, Motera       17
19        20                                   Barabati Stadium       18
20        21       Vidarbha Cricket Association Stadium, Jamtha       19
21        22       Himachal Pradesh Cricket Association Stadium       20
22        23                                      Nehru Stadium       21
23        24                             Holkar Cricket Stadium       22
24        25  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...       23
25        26                         Subrata Roy Sahara Stadium       24
26        27   Shaheed Veer Narayan Singh International Stadium       25
27        28                 JSCA International Stadium Complex       26
28        29                               Sheikh Zayed Stadium       27
29        30                            Sharjah Cricket Stadium       27
30        31                Dubai International Cricket Stadium       27
31        32            Maharashtra Cricket Association Stadium       24
32        33  Punjab Cricket Association IS Bindra Stadium, ...        2
33        34             Saurashtra Cricket Association Stadium       28
34        35                                         Green Park       29

Table: Extra_Type

   Extra_Id Extra_Name
0         1    legbyes
1         2      wides
2         3       byes
3         4    noballs
4         5    penalty

Table: Out_Type

   Out_Id               Out_Name
0       1                 caught
1       2                 bowled
2       3                run out
3       4                    lbw
4       5           retired hurt
5       6                stumped
6       7      caught and bowled
7       8             hit wicket
8       9  obstructing the field

Table: Toss_Decision

   Toss_Id Toss_Name
0        1     field
1        2       bat

Table: Umpire

    Umpire_Id            Umpire_Name  Umpire_Country
0           1              Asad Rauf               6
1           2              MR Benson              10
2           3              Aleem Dar               6
3           4               SJ Davis              10
4           5              BF Bowden               4
5           6              IL Howell               2
6           7              DJ Harper               5
7           8            RE Koertzen               2
8           9            BR Doctrove               8
9          10         AV Jayaprakash               1
10         11             BG Jerling               2
11         12              M Erasmus               2
12         13        HDPK Dharmasena               7
13         14               S Asnani               1
14         15             GAV Baxter               4
15         16              SS Hazare               1
16         17            K Hariharan               1
17         18             SL Shastri               1
18         19            SK Tarapore               1
19         20                 S Ravi               1
20         21             SJA Taufel               5
21         22                  S Das               1
22         23              AM Saheba               1
23         24             PR Reiffel               5
24         25              JD Cloete               2
25         26           AK Chaudhary               1
26         27            VA Kulkarni               1
27         28           BNJ Oxenford               5
28         29              CK Nandan               1
29         30          C Shamshuddin               1
30         31               NJ Llong              10
31         32         RK Illingworth              10
32         33           RM Deshpande               1
33         34              K Srinath               1
34         35                 SD Fry               5
35         36            CB Gaffaney               4
36         37              PG Pathak               1
37         38            Nitin Menon               1
38         39             K Bharatan               1
39         40            AY Dandekar               1
40         41  KN Ananthapadmanabhan               1
41         42         A Nand Kishore               1
42         43         GA Pratapkumar               1
43         44              RB Tiffin               9
44         45              I Shivram               1
45         46              SD Ranade               1
46         47         TH Wijewardene               7
47         48                AL Hill               4
48         49              RJ Tucker               5
49         50            Subroto Das               1
50         51           K Srinivasan               1
51         52              VK Sharma               1

Table: Team

    Team_Id                    Team_Name
0         1        Kolkata Knight Riders
1         2  Royal Challengers Bangalore
2         3          Chennai Super Kings
3         4              Kings XI Punjab
4         5             Rajasthan Royals
5         6             Delhi Daredevils
6         7               Mumbai Indians
7         8              Deccan Chargers
8         9         Kochi Tuskers Kerala
9        10                Pune Warriors
10       11          Sunrisers Hyderabad
11       12      Rising Pune Supergiants
12       13                Gujarat Lions

Table: Ball_by_Ball

,Match_Id,Over_Id,Ball_Id,Innings_No,Team_Batting,Team_Bowling,Striker_Batting_Position,Striker,Non_Striker,Bowler
0,335987,1,1,1,1,2,1,1,2,14
1,335987,1,1,2,2,1,1,6,7,106
2,335987,1,2,1,1,2,2,2,1,14
3,335987,1,2,2,2,1,2,7,6,106
4,335987,1,3,1,1,2,2,2,1,14
...,...,...,...,...,...,...,...,...,...,...
136585,981024,20,4,2,2,11,9,140,369,299
136586,981024,20,5,1,11,2,9,299,385,32
136587,981024,20,5,2,2,11,6,369,140,299
136588,981024,20,6,1,11,2,7,385,299,32
136589,981024,20,6,2,2,11,9,140,369,299

Table: Match

,Match_Id,Team_1,Team_2,Match_Date,Season_Id,Venue_Id,Toss_Winner,Toss_Decide,Win_Type,Win_Margin,Outcome_type,Match_Winner,Man_of_the_Match
0,335987,2,1,2008-04-18 00:00:00,1,1,2,1,1,140.0,1,1.0,2.0
1,335988,4,3,2008-04-19 00:00:00,1,2,3,2,1,33.0,1,3.0,19.0
2,335989,6,5,2008-04-19 00:00:00,1,3,5,2,2,9.0,1,6.0,90.0
3,335990,7,2,2008-04-20 00:00:00,1,4,7,2,2,5.0,1,2.0,11.0
4,335991,1,8,2008-04-20 00:00:00,1,5,8,2,2,5.0,1,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,981016,6,2,2016-05-22 00:00:00,9,27,2,1,2,6.0,1,2.0,8.0
573,981018,13,2,2016-05-24 00:00:00,9,1,2,1,2,4.0,1,2.0,110.0
574,981020,11,1,2016-05-25 00:00:00,9,3,1,1,1,22.0,1,11.0,163.0
575,981022,13,11,2016-05-27 00:00:00,9,3,11,1,2,4.0,1,11.0,187.0
576,981024,2,11,2016-05-29 00:00:00,9,1,11,2,1,8.0,1,11.0,385.0

Table: Rolee

   Role_Id      Role_Desc
0        1        Captain
1        2         Keeper
2        3         Player
3        4  CaptainKeeper

Table: Player_Match

       Match_Id  Player_Id  Role_Id  Team_Id
0        335987          1        1        1
1        335987          2        3        1
2        335987          3        3        1
3        335987          4        3        1
4        335987          5        3        1
...         ...        ...      ...      ...
12689    981024        385        3       11
12690    981024        394        3       11
12691    981024        429        3       11
12692    981024        434        3        2
12693    981024        460        3       11

[12694 rows x 4 columns]

In [4]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("sql-murder-mystery.db")

df1 = pd.read_sql("SELECT * FROM person", conn)
print("PERSON")
display(df1.head())

df2 = pd.read_sql("SELECT * FROM interview", conn)
print("INTERVIEW")
display(df2.tail())

df3 = pd.read_sql("SELECT * FROM crime_scene_report", conn)
print("CRIME SCENE REPORT")
display(df3)

df4 = pd.read_sql("SELECT * FROM income", conn)
print("INCOME")
display(df4.describe(include="all"))

conn.close()

Table: crime_scene_report

,date,type,description,city
0,20180115,robbery,A Man Dressed as Spider-Man Is on a Robbery Spree,NYC
1,20180115,murder,Life? Dont talk to me about life.,Albany
2,20180115,murder,"Mama, I killed a man, put a gun against his he...",Reno
3,20180215,murder,REDACTED REDACTED REDACTED,SQL City
4,20180215,murder,Someone killed the guard! He took an arrow to ...,SQL City
...,...,...,...,...
1223,20180430,bribery,\n,Garden Grove
1224,20180430,fraud,‘Why not?’ said the March Hare.\n,Houma
1225,20180430,assault,\n,Fontana
1226,20180501,assault,be NO mistake about it: it was neither more no...,Trenton
1227,20180115,murder,Security footage shows that there were 2 witne...,SQL City

Table: drivers_license

,id,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
0,100280,72,57,brown,red,male,P24L4U,Acura,MDX
1,100460,63,72,brown,brown,female,XF02T6,Cadillac,SRX
2,101029,62,74,green,green,female,VKY5KR,Scion,xB
3,101198,43,54,amber,brown,female,Y5NZ08,Nissan,Rogue
4,101255,18,79,blue,grey,female,5162Z1,Lexus,GS
...,...,...,...,...,...,...,...,...,...
10002,999923,19,77,amber,black,female,5L0ZI4,GMC,Sierra 3500
10003,999940,71,61,green,green,male,1B8QN8,Mitsubishi,Eclipse
10004,999981,67,69,brown,blue,female,1684K3,Land Rover,LR2
10005,999986,49,58,green,grey,male,F8F64H,Lexus,LS
10006,999993,18,63,black,black,female,6UZO2O,Cadillac,DeVille

Table: person

,id,name,license_id,address_number,address_street_name,ssn
0,10000,Christoper Peteuil,993845,624,Bankhall Ave,747714076
1,10007,Kourtney Calderwood,861794,2791,Gustavus Blvd,477972044
2,10010,Muoi Cary,385336,741,Northwestern Dr,828638512
3,10016,Era Moselle,431897,1987,Wood Glade St,614621061
4,10025,Trena Hornby,550890,276,Daws Hill Way,223877684
...,...,...,...,...,...,...
10006,99936,Luba Benser,274427,680,Carnage Blvd,685095054
10007,99941,Roxana Mckimley,975942,1613,Gate St,512136801
10008,99965,Cherie Zeimantz,287627,3661,The Water Ave,362877324
10009,99982,Allen Cruse,251350,3126,N Jean Dr,348734531
10010,99990,Vance Hunten,830407,3056,Lancefield St,896677562

Table: facebook_event_checkin

,person_id,event_id,event_name,date
0,28508,5880,Nudists are people who wear one-button suits.\n,20170913
1,63713,3865,but that's because it's the best book on anyth...,20171009
2,63713,3999,"If Murphy's Law can go wrong, it will.\n",20170502
3,63713,6436,Old programmers never die. They just branch t...,20170926
4,82998,4470,Help a swallow land at Capistrano.\n,20171022
...,...,...,...,...
20006,99716,1143,SQL Symphony Concert,20171206
20007,99716,1143,SQL Symphony Concert,20171212
20008,99716,1143,SQL Symphony Concert,20171229
20009,67318,4719,The Funky Grooves Tour,20180115
20010,67318,1143,SQL Symphony Concert,20171206

Table: interview

      person_id                                         transcript
0         28508                ‘I deny it!’ said the March Hare.\n
1         63713                                                 \n
2         86208      way, and the whole party swam to the shore.\n
3         35267  lessons in here? Why, there’s hardly room for ...
4         33856                                                 \n
...         ...                                                ...
4986      37357  Alice did not wish to offend the Dormouse agai...
4987      10206  time,’ she said, ‘than waste it in asking ridd...
4988      14887  I heard a gunshot and then saw a man run out. ...
4989      16371  I saw the murder happen, and I recognized the ...
4990      67318  I was hired by a woman with a lot of money. I ...

[4991 rows x 2 columns]

Table: get_fit_now_member

,id,person_id,name,membership_start_date,membership_status
0,NL318,65076,Everette Koepke,20170926,gold
1,AOE21,39426,Noe Locascio,20171005,regular
2,2PN28,63823,Jeromy Heitschmidt,20180215,silver
3,0YJ24,80651,Waneta Wellard,20171206,gold
4,3A08L,32858,Mei Bianchin,20170401,silver
...,...,...,...,...,...
179,2V137,41693,Wendell Dulany,20171219,silver
180,4KB72,79110,Emile Hege,20170522,regular
181,48Z7A,28819,Joe Germuska,20160305,gold
182,48Z55,67318,Jeremy Bowers,20160101,gold
183,90081,16371,Annabel Miller,20160208,gold

Table: get_fit_now_check_in

     membership_id  check_in_date  check_in_time  check_out_time
0            NL318       20180212            329             365
1            NL318       20170811            469             920
2            NL318       20180429            506             554
3            NL318       20180128            124             759
4            NL318       20171027            418            1019
...            ...            ...            ...             ...
2698         4KB72       20170422           1016            1114
2699         4KB72       20170630            408             885
2700         48Z7A       20180109           1600            1730
2701         48Z55       20180109           1530            1700
2702         90081       20180109           1600            1700

[2703 rows x 4 columns]

Table: income

            ssn  annual_income
0     100009868          52200
1     100169584          64500
2     100300433          74400
3     100355733          35900
4     100366269          73000
...         ...            ...
7509  999679296          54400
7510  999762859          77000
7511  999824984          82000
7512  999910617          82600
7513  999942603          11500

[7514 rows x 2 columns]

Table: solution

Empty DataFrame
Columns: [user, value]
Index: []

In [13]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("olist.sqlite")

df1 = pd.read_sql("SELECT * FROM customers", conn)
print("TABLE 1: customers")
display(df1.head())

df2 = pd.read_sql("SELECT * FROM orders", conn)
print("TABLE 2: orders")
display(df2.tail())

df3 = pd.read_sql("SELECT * FROM products", conn)
print("TABLE 3: products")
display(df3)


df4 = pd.read_sql("SELECT * FROM order_payments", conn)
print("TABLE 4: order_payments")
display(df4.describe(include="all"))

conn.close()

TABLE 1: customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

TABLE 2: orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

TABLE 3: products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

TABLE 4: order_payments

,order_id,payment_sequential,payment_type,payment_installments,payment_value
count,103886,103886.000000,103886,103886.000000,103886.000000
unique,99440,NaN,5,NaN,NaN
top,fa65dad1b0e818e3ccc5cb0e39231352,NaN,credit_card,NaN,NaN
freq,29,NaN,76795,NaN,NaN
mean,NaN,1.092679,NaN,2.853349,154.100380
std,NaN,0.706584,NaN,2.687051,217.494064
min,NaN,1.000000,NaN,0.000000,0.000000
25%,NaN,1.000000,NaN,1.000000,56.790000
50%,NaN,1.000000,NaN,1.000000,100.000000
75%,NaN,1.000000,NaN,4.000000,171.837500
max,NaN,29.000000,NaN,24.000000,13664.080000